theme: jekyll-theme-architect

title: [security-spec]
description: [Java EE Security API specification (JSR 375)]

# sidebar links url
links:
  source: https://github.com/javaee/security-spec
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

